services:
  - type: web
    name: mysite
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bokeh serve --show cofs_photocatalysis.py --allow-websocket-origin=mysite-c05b.onrender.com"
